Showcase for a bug with using fun { ... } inside of methods of reified classes.
The error is:
Cause: java.lang.NoSuchMethodError: scala.js.ClassesProg$FooFun$$anonfun$producer$1.<init>(Lscala/js/ClassesProg$FooFun$bis;)V
  at scala.js.ClassesProg$FooFun$bis.producer(TestClasses.scala:33)

The problem is that I have to rename FooFun to FooFun$bis when I
rewrite it to make the class loader happy, as it doesn't like when
there are multiple implementations for a class name. But now, all
those weird helpers generated by Scala still take FooFun, not
FooFun$bis...

Not sure how to solve this cleanly. Maybe I can make FooFun$bis a
subclass of FooFun?